# Generated by Django 5.2.8 on 2026-08-12 17:44

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0004_remove_job_car_type_job_vehicle_type_and_more'),
        ('payments', '0004_remove_payment_transaction_id_payment_mpesa_receipt_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='payment',
            name='payments_pa_status_7ad4af_idx',
        ),
        migrations.RemoveIndex(
            model_name='payment',
            name='payments_pa_method_70cfb8_idx',
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['status', 'paid_at'], name='payments_pa_status_bed4b8_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['checkout_request_id'], name='payments_pa_checkou_e4cf10_idx'),
        ),
    ]
