# Generated by Django 5.2.8 on 2026-04-10 16:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_alter_job_id'),
        ('vehicles', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='car_type',
        ),
        migrations.AddField(
            model_name='job',
            name='vehicle_type',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, to='vehicles.vehicletype'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='job',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('paid', 'Paid')], db_index=True, default='pending', max_length=20),
        ),
    ]
